from django.urls import path

from .views import (
    CVAdaptApplyView,
    CVAdaptPreviewView,
    CVAIImproveView,
    CVAssistantChatView,
    CVAssistantFinalizeView,
    CVContextUploadView,
    CVCoverLetterDownloadView,
    CVCoverLetterView,
    CVDetailView,
    CVDownloadView,
    CVDuplicateView,
    CVGenerateView,
    CVListCreateView,
    CVCorrectView,
    CVPlansView,
    CVPreviewView,
    CVProfileView,
    CVPublicView,
    CVRewriteView,
    CVSetReferenceView,
    CVShareView,
    PaymentInitializeView,
    PaymentVerifyView,
    PaystackWebhookView,
)

urlpatterns = [
    path("", CVListCreateView.as_view(), name="cv-list-create"),
    path("preview/", CVPreviewView.as_view(), name="cv-preview"),
    path("assistant/chat/", CVAssistantChatView.as_view(), name="cv-assistant-chat"),
    path("assistant/finalize/", CVAssistantFinalizeView.as_view(), name="cv-assistant-finalize"),
    path("rewrite/", CVRewriteView.as_view(), name="cv-rewrite"),
    path("profile/", CVProfileView.as_view(), name="cv-profile"),
    path("correct/", CVCorrectView.as_view(), name="cv-correct"),
    path("plans/", CVPlansView.as_view(), name="cv-plans"),
    path("public/<str:slug>/", CVPublicView.as_view(), name="cv-public"),
    path("payments/initialize/", PaymentInitializeView.as_view(), name="payment-initialize"),
    path("payments/verify/", PaymentVerifyView.as_view(), name="payment-verify"),
    path("payments/paystack-webhook/", PaystackWebhookView.as_view(), name="paystack-webhook"),
    path("<int:pk>/", CVDetailView.as_view(), name="cv-detail"),
    path("<int:pk>/context/", CVContextUploadView.as_view(), name="cv-context"),
    path("<int:pk>/ai/improve/", CVAIImproveView.as_view(), name="cv-ai-improve"),
    path("<int:pk>/adapt/", CVAdaptPreviewView.as_view(), name="cv-adapt-preview"),
    path("<int:pk>/adapt/apply/", CVAdaptApplyView.as_view(), name="cv-adapt-apply"),
    path("<int:pk>/reference/", CVSetReferenceView.as_view(), name="cv-set-reference"),
    path("<int:pk>/share/", CVShareView.as_view(), name="cv-share"),
    path("<int:pk>/cover-letter/", CVCoverLetterView.as_view(), name="cv-cover-letter"),
    path("<int:pk>/cover-letter/download/", CVCoverLetterDownloadView.as_view(), name="cv-cover-letter-download"),
    path("<int:pk>/generate/", CVGenerateView.as_view(), name="cv-generate"),
    path("<int:pk>/duplicate/", CVDuplicateView.as_view(), name="cv-duplicate"),
    path("<int:pk>/download/", CVDownloadView.as_view(), name="cv-download"),
]
