"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-s9w6iv3^$qdp2*wdyg=im21c+-+vrbmhxp!o36$kj5%kv5!q#j')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'true').lower() == 'true'

ALLOWED_HOSTS = [host.strip() for host in os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    "django.contrib.admin",
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'users',
    'templates',
    'cvs',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# WhiteNoise (sert les fichiers statiques en production) : ajouté seulement s'il
# est installé, juste après SecurityMiddleware.
try:
    import whitenoise  # noqa: F401

    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")
    _WHITENOISE = True
except ImportError:
    _WHITENOISE = False

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
        if _WHITENOISE
        else "django.contrib.staticfiles.storage.StaticFilesStorage"
    },
}
MEDIA_URL = "media/"
MEDIA_ROOT = Path(os.getenv("DJANGO_MEDIA_ROOT") or (BASE_DIR / "media"))


# CORS : origines locales + celles fournies en production (DJANGO_CORS_ORIGINS, séparées par des virgules)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "http://localhost:5180",
    "http://127.0.0.1:5180",
]
CORS_ALLOWED_ORIGINS += [o.strip() for o in os.getenv("DJANGO_CORS_ORIGINS", "").split(",") if o.strip()]
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()]

# Production : derrière un proxy HTTPS (Render, Railway…)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Base de données : Postgres via DATABASE_URL en production, sinon SQLite en local.
_database_url = os.getenv("DATABASE_URL", "")
if _database_url:
    try:
        import dj_database_url

        DATABASES = {"default": dj_database_url.parse(_database_url, conn_max_age=600, ssl_require=True)}
    except Exception:
        pass

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# JWT : sessions longue durée. L'utilisateur reste connecté tant qu'il ne se
# déconnecte pas lui-même. Le token d'accès dure longtemps, et le refresh
# (avec rotation) prolonge la session à chaque utilisation.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=int(os.getenv("JWT_ACCESS_DAYS", "30"))),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.getenv("JWT_REFRESH_DAYS", "365"))),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,
}


# IA CV
AI_PROVIDER = os.getenv("AI_PROVIDER", "groq").lower()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-5.5")

GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
GROQ_MODEL = os.getenv("GROQ_MODEL", "openai/gpt-oss-120b")
# Quota tokens/minute du palier Groq (gratuit = 8000). On garde une marge.
# Relever cette valeur après passage au palier Dev de Groq.
GROQ_TPM_LIMIT = int(os.getenv("GROQ_TPM_LIMIT", "7600"))

OPENAI_REQUEST_TIMEOUT = int(os.getenv("OPENAI_REQUEST_TIMEOUT", "60"))
CV_OCR_LANGUAGES = os.getenv("CV_OCR_LANGUAGES", "fra+eng")
CV_OCR_MAX_PAGES = int(os.getenv("CV_OCR_MAX_PAGES", "6"))
CV_OCR_DPI = int(os.getenv("CV_OCR_DPI", "180"))

# Paystack
PAYSTACK_SECRET_KEY = os.getenv("PAYSTACK_SECRET_KEY", "")
PAYSTACK_PUBLIC_KEY = os.getenv("PAYSTACK_PUBLIC_KEY", "")
PAYSTACK_CURRENCY = os.getenv("PAYSTACK_CURRENCY", "XOF")
PAYSTACK_CALLBACK_URL = os.getenv("PAYSTACK_CALLBACK_URL", "http://localhost:5173/dashboard")
PAYSTACK_SUBUNIT_MULTIPLIER = int(os.getenv("PAYSTACK_SUBUNIT_MULTIPLIER", "1"))
PAYMENTS_ENFORCED = os.getenv("PAYMENTS_ENFORCED", "false" if DEBUG else "true").lower() == "true"

# Génération PDF
LIBREOFFICE_BINARY = os.getenv("LIBREOFFICE_BINARY", "soffice")
CV_HTML_RENDERER = os.getenv("CV_HTML_RENDERER", "auto").lower()
CV_CHROMIUM_BINARY = os.getenv("CV_CHROMIUM_BINARY", "")
CV_SINGLE_PRICE_XOF = int(os.getenv("CV_SINGLE_PRICE_XOF", "200"))
CV_WEEKLY_PRICE_XOF = int(os.getenv("CV_WEEKLY_PRICE_XOF", "1000"))
CV_EXTRA_AI_PRICE_XOF = int(os.getenv("CV_EXTRA_AI_PRICE_XOF", "50"))
CV_SINGLE_ACCESS_HOURS = int(os.getenv("CV_SINGLE_ACCESS_HOURS", "2"))
CV_WEEKLY_ACCESS_HOURS = int(os.getenv("CV_WEEKLY_ACCESS_HOURS", "168"))
CV_EXTRA_AI_CREDITS = int(os.getenv("CV_EXTRA_AI_CREDITS", "1"))

# Modèle commercial : essai gratuit à l'inscription, puis abonnement hebdomadaire.
CV_TRIAL_DAYS = int(os.getenv("CV_TRIAL_DAYS", "7"))
CV_WEEKLY_CV_CREDITS = int(os.getenv("CV_WEEKLY_CV_CREDITS", "5"))

# Dossier où déposer vos modèles Word personnalisés
CV_TEMPLATE_LIBRARY_DIR = Path(os.getenv("CV_TEMPLATE_LIBRARY_DIR") or BASE_DIR / "cvs" / "docx_templates" / "examples")
