# Generated by Django 6.0.3 on 2026-07-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0006_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='is_reference',
            field=models.BooleanField(default=False),
        ),
    ]
