# Generated by Django 6.0.3 on 2026-09-18 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0007_cv_cover_letter_cv_is_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('sample_value', models.TextField(blank=True)),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'À examiner'), ('added', 'Ajouté au modèle'), ('dismissed', 'Ignoré')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_suggestions', to='cvs.cv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suggestion de champ',
                'verbose_name_plural': 'Suggestions de champs',
                'ordering': ['-occurrences', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_pdf', models.FileField(upload_to='template_submissions/')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='template_submissions/previews/')),
                ('aesthetic_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('aesthetic_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'À examiner'), ('approved', 'Retenu'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_submissions', to='cvs.cv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CV importé au design retenu',
                'verbose_name_plural': 'CV importés au design retenu',
                'ordering': ['-aesthetic_score', '-created_at'],
            },
        ),
    ]
