# Generated by Django 6.0.3 on 2026-09-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0008_fieldsuggestion_templatesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cv',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='public_view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
